---
DNS1: 192.160.1.254
DNS2: 1.1.1.1
dnsmasq:
  customDnsEntries:
    - address=/homelab-0/192.168.1.64
    - address=/homelab-1/192.168.1.67
persistentVolumeClaim:
  enabled: true
  storageClassName: longhorn
ingress:
  ingressClassName: nginx-internal
  enabled: true
  hosts: [pihole.home]
serviceWeb:
  loadBalancerIP: 192.168.1.250
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer
serviceDns:
  loadBalancerIP: 192.168.1.250
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer
replicaCount: 1
